#!/usr/bin/env bash
echo "== list objects"

#Check fo bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided. Please enter bucket name:"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \